import {
  bulkTriage,
  classifyThreads,
  draftReply,
  extractActionItems,
  nlSearch,
  nlTask,
  preSendCritique,
  summarizeThread,
  translateThread,
  triageThread,
} from './ai';
import {
  albatrossApplyIntentPlan,
  albatrossApproveAction,
  albatrossCreateProject,
  albatrossCreateRoutine,
  albatrossCreateSprint,
  albatrossGetProjectPane,
  albatrossListApprovalQueue,
  albatrossListProjects,
  albatrossListRoutines,
  albatrossListSprints,
  albatrossPreviewUndoUnresolved,
  albatrossRejectAction,
  albatrossRunRoutineNow,
  albatrossSetRoutineConsent,
  albatrossUndoApproval,
  albatrossUpdateProject,
} from './albatross';
import {
  areaAddFact,
  areaArchive,
  areaArtifactSetStatus,
  areaCreate,
  areaDiscoverContext,
  areaDomainActivity,
  areaFactSetStatus,
  areaHome,
  areaList,
  areaUpdateIdentity,
  workHome,
} from './areas';
import { listAuditEntries, logAction } from './audit-tools';
import {
  calendarCountEvents,
  calendarCreateEvent,
  calendarDeleteEvent,
  calendarDeleteRecurringSeries,
  calendarEventDetail,
  calendarFreeBusy,
  calendarGetPrimary,
  calendarListCalendars,
  calendarListEvents,
  calendarRsvpEvent,
  calendarSearchEvents,
  calendarSuggestTimes,
  calendarSyncNow,
  calendarUnsubscribeCalendar,
  calendarUpdateEvent,
} from './calendar';
import {
  cancelScheduled,
  deleteDraftTool,
  forwardMessage,
  listDraftsTool,
  listScheduled,
  replyAllMessage,
  replyMessage,
  saveDraftTool,
  scheduleSend,
  sendMessage,
  undoSend,
  updateDraft,
} from './compose';
import { contactLookup, expandAlias } from './contacts';
import { corpusCount, corpusSearch, senderProfile, threadTimeline } from './corpus';
import {
  dismissDailyReportTaskTool,
  dismissDailyReportThreadTool,
  generateDailyReportTool,
  getDailyReportTool,
  getLatestDailyReportTool,
  listDailyReportsTool,
  listDailyReportTaskDismissalsTool,
  listDailyReportThreadDismissalsTool,
  restoreDailyReportTaskTool,
  restoreDailyReportThreadTool,
} from './daily-report';
import { DISPLAY_TOOLS } from './display';
import {
  getMessage,
  getSmartCategoryStats,
  getThread,
  listAccounts,
  listAccountThreads,
  listAttachments,
  listLabels,
  listSmartCategory,
  readThread,
  recentThreadsCached,
  searchThreads,
} from './mail';
import {
  addLabel,
  applySmartLabels,
  archiveThread,
  createLabel,
  markRead,
  markThreadRead,
  markUnread,
  muteThread,
  removeLabel,
  restoreFromTrash,
  setSmartCategoryTool,
  snoozeThreadTool,
  starMessage,
  trashThread,
  unsnoozeThreadTool,
  unstarMessage,
} from './mail-mutate';
import { githubSearch, mcpConnectionStatus, mcpCreateTask, mcpListItems, mcpSearch } from './mcp';
import { forget, listMemories, recall, remember } from './memories';
import { listRecentOperationsTool, undoOperationTool } from './operations-tools';
import { resolvePhotos } from './photos';
import type { AnyTool } from './registry';
import { salvageContext } from './salvage';
import {
  applySmartCorrection,
  createSmartLabel,
  createSmartRule,
  deleteSmartLabel,
  listSmartLabels,
  listSmartRules,
  markSenderHuman,
  previewSmartLabel,
  setSmartRuleEnabledTool,
  updateSmartLabel,
} from './smart-labels';
import {
  tasksAddComment,
  tasksAttachCalendarEventLink,
  tasksAttachFile,
  tasksAttachLink,
  tasksCreateBoard,
  tasksCreateCard,
  tasksCreateColumn,
  tasksDeleteBoard,
  tasksDeleteCard,
  tasksDeleteColumn,
  tasksDueCards,
  tasksForCalendarEvent,
  tasksForThread,
  tasksGetBoard,
  tasksGetCard,
  tasksInviteMember,
  tasksListBoards,
  tasksMoveCard,
  tasksRemoveMember,
  tasksRenameBoard,
  tasksRenameColumn,
  tasksReorderColumn,
  tasksSetPublicLink,
  tasksUpdateCard,
} from './tasks';
import {
  getTrackedThreadTool,
  listTrackedThreadsTool,
  resolveTrackedThread,
  trackThread,
  updateTrackedThreadTool,
} from './tracked-threads';
import {
  uiCloseBar,
  uiFocusThread,
  uiOpenCompose,
  uiOpenReply,
  uiSetQuery,
  uiSwitchAccount,
  uiToast,
} from './ui-tools';
import { browserbaseFetch, browserbaseSearch } from './web';

const allTools: AnyTool[] = [
  mcpSearch,
  githubSearch,
  mcpListItems,
  mcpConnectionStatus,
  mcpCreateTask,
  listAccounts,
  searchThreads,
  corpusSearch,
  senderProfile,
  corpusCount,
  threadTimeline,
  listSmartCategory,
  getSmartCategoryStats,
  getThread,
  readThread,
  getMessage,
  listLabels,
  listAttachments,
  recentThreadsCached,
  listAccountThreads,
  archiveThread,
  trashThread,
  restoreFromTrash,
  markRead,
  markThreadRead,
  markUnread,
  starMessage,
  unstarMessage,
  addLabel,
  removeLabel,
  createLabel,
  applySmartLabels,
  applySmartCorrection,
  markSenderHuman,
  setSmartCategoryTool,
  muteThread,
  snoozeThreadTool,
  unsnoozeThreadTool,
  sendMessage,
  replyMessage,
  replyAllMessage,
  forwardMessage,
  saveDraftTool,
  updateDraft,
  deleteDraftTool,
  listDraftsTool,
  listScheduled,
  scheduleSend,
  cancelScheduled,
  undoSend,
  summarizeThread,
  triageThread,
  draftReply,
  bulkTriage,
  classifyThreads,
  generateDailyReportTool,
  getLatestDailyReportTool,
  listDailyReportsTool,
  getDailyReportTool,
  dismissDailyReportTaskTool,
  listDailyReportTaskDismissalsTool,
  dismissDailyReportThreadTool,
  listDailyReportThreadDismissalsTool,
  restoreDailyReportTaskTool,
  restoreDailyReportThreadTool,
  listSmartLabels,
  createSmartLabel,
  previewSmartLabel,
  updateSmartLabel,
  deleteSmartLabel,
  listSmartRules,
  createSmartRule,
  setSmartRuleEnabledTool,
  trackThread,
  updateTrackedThreadTool,
  resolveTrackedThread,
  listTrackedThreadsTool,
  getTrackedThreadTool,
  extractActionItems,
  translateThread,
  preSendCritique,
  nlSearch,
  nlTask,
  remember,
  recall,
  forget,
  listMemories,
  calendarFreeBusy,
  calendarSuggestTimes,
  calendarCreateEvent,
  calendarListCalendars,
  calendarListEvents,
  calendarSearchEvents,
  calendarCountEvents,
  calendarEventDetail,
  calendarSyncNow,
  calendarUpdateEvent,
  calendarDeleteEvent,
  calendarDeleteRecurringSeries,
  calendarRsvpEvent,
  calendarGetPrimary,
  calendarUnsubscribeCalendar,
  contactLookup,
  expandAlias,
  resolvePhotos,
  browserbaseSearch,
  browserbaseFetch,
  logAction,
  listAuditEntries,
  listRecentOperationsTool,
  undoOperationTool,
  tasksListBoards,
  tasksGetBoard,
  tasksGetCard,
  tasksForThread,
  tasksForCalendarEvent,
  tasksDueCards,
  albatrossApplyIntentPlan,
  albatrossListApprovalQueue,
  albatrossApproveAction,
  albatrossRejectAction,
  albatrossUndoApproval,
  albatrossCreateProject,
  albatrossListProjects,
  albatrossUpdateProject,
  albatrossCreateRoutine,
  albatrossListRoutines,
  albatrossSetRoutineConsent,
  albatrossRunRoutineNow,
  albatrossGetProjectPane,
  albatrossCreateSprint,
  albatrossListSprints,
  albatrossPreviewUndoUnresolved,
  salvageContext,
  areaList,
  areaHome,
  workHome,
  areaCreate,
  areaDiscoverContext,
  areaUpdateIdentity,
  areaArchive,
  areaArtifactSetStatus,
  areaAddFact,
  areaFactSetStatus,
  areaDomainActivity,
  tasksCreateBoard,
  tasksCreateCard,
  tasksUpdateCard,
  tasksMoveCard,
  tasksDeleteCard,
  tasksCreateColumn,
  tasksRenameColumn,
  tasksReorderColumn,
  tasksDeleteColumn,
  tasksRenameBoard,
  tasksDeleteBoard,
  tasksSetPublicLink,
  tasksInviteMember,
  tasksRemoveMember,
  tasksAddComment,
  tasksAttachCalendarEventLink,
  tasksAttachLink,
  tasksAttachFile,
  // UI tools — server returns ack, client intercepts for the real mutation.
  uiFocusThread,
  uiSetQuery,
  uiOpenCompose,
  uiOpenReply,
  uiToast,
  uiCloseBar,
  uiSwitchAccount,
  // Display tools — validated payloads rendered as rich tool-ui components in
  // chat (weather, charts, tables, code, media, maps, drafts…).
  ...DISPLAY_TOOLS,
];

export const TOOLS: Record<string, AnyTool> = Object.fromEntries(allTools.map((t) => [t.name, t]));

export function listToolMetadata() {
  return allTools.map((t) => ({
    name: t.name,
    description: t.description,
    category: t.category,
    mutating: t.mutating,
  }));
}

export function getTool(name: string): AnyTool | null {
  return TOOLS[name] || null;
}
