import {
  bulkTriage,
  classifyThreads,
  draftReply,
  extractActionItems,
  nlSearch,
  preSendCritique,
  summarizeThread,
  translateThread,
  triageThread,
} from './ai';
import { listAuditEntries, logAction } from './audit-tools';
import {
  calendarCreateEvent,
  calendarDeleteEvent,
  calendarDeleteRecurringSeries,
  calendarFreeBusy,
  calendarGetPrimary,
  calendarListCalendars,
  calendarListEvents,
  calendarRsvpEvent,
  calendarSuggestTimes,
  calendarSyncNow,
  calendarUnsubscribeCalendar,
  calendarUpdateEvent,
} from './calendar';
import {
  cancelScheduled,
  deleteDraftTool,
  forwardMessage,
  listDraftsTool,
  listScheduled,
  replyAllMessage,
  replyMessage,
  saveDraftTool,
  scheduleSend,
  sendMessage,
  undoSend,
  updateDraft,
} from './compose';
import { contactLookup, expandAlias } from './contacts';
import { corpusCount, corpusSearch, senderProfile, threadTimeline } from './corpus';
import {
  generateDailyReportTool,
  getDailyReportTool,
  getLatestDailyReportTool,
  listDailyReportsTool,
} from './daily-report';
import {
  getMessage,
  getSmartCategoryStats,
  getThread,
  listAccounts,
  listAccountThreads,
  listAttachments,
  listLabels,
  listSmartCategory,
  readThread,
  recentThreadsCached,
  searchThreads,
} from './mail';
import {
  addLabel,
  applySmartLabels,
  archiveThread,
  createLabel,
  markRead,
  markThreadRead,
  markUnread,
  muteThread,
  removeLabel,
  restoreFromTrash,
  setSmartCategoryTool,
  snoozeThreadTool,
  starMessage,
  trashThread,
  unsnoozeThreadTool,
  unstarMessage,
} from './mail-mutate';
import { forget, listMemories, recall, remember } from './memories';
import { listRecentOperationsTool, undoOperationTool } from './operations-tools';
import { resolvePhotos } from './photos';
import type { AnyTool } from './registry';
import {
  applySmartCorrection,
  createSmartLabel,
  createSmartRule,
  deleteSmartLabel,
  listSmartLabels,
  listSmartRules,
  markSenderHuman,
  previewSmartLabel,
  setSmartRuleEnabledTool,
  updateSmartLabel,
} from './smart-labels';
import {
  tasksAddComment,
  tasksAttachFile,
  tasksAttachLink,
  tasksCreateBoard,
  tasksCreateCard,
  tasksCreateColumn,
  tasksDeleteBoard,
  tasksDeleteCard,
  tasksDeleteColumn,
  tasksGetBoard,
  tasksListBoards,
  tasksMoveCard,
  tasksRenameBoard,
  tasksRenameColumn,
  tasksUpdateCard,
} from './tasks';
import {
  getTrackedThreadTool,
  listTrackedThreadsTool,
  resolveTrackedThread,
  trackThread,
  updateTrackedThreadTool,
} from './tracked-threads';
import {
  uiCloseBar,
  uiFocusThread,
  uiOpenCompose,
  uiOpenReply,
  uiSetQuery,
  uiSwitchAccount,
  uiToast,
} from './ui-tools';
import { browserbaseFetch, browserbaseSearch } from './web';

const allTools: AnyTool[] = [
  listAccounts,
  searchThreads,
  corpusSearch,
  senderProfile,
  corpusCount,
  threadTimeline,
  listSmartCategory,
  getSmartCategoryStats,
  getThread,
  readThread,
  getMessage,
  listLabels,
  listAttachments,
  recentThreadsCached,
  listAccountThreads,
  archiveThread,
  trashThread,
  restoreFromTrash,
  markRead,
  markThreadRead,
  markUnread,
  starMessage,
  unstarMessage,
  addLabel,
  removeLabel,
  createLabel,
  applySmartLabels,
  applySmartCorrection,
  markSenderHuman,
  setSmartCategoryTool,
  muteThread,
  snoozeThreadTool,
  unsnoozeThreadTool,
  sendMessage,
  replyMessage,
  replyAllMessage,
  forwardMessage,
  saveDraftTool,
  updateDraft,
  deleteDraftTool,
  listDraftsTool,
  listScheduled,
  scheduleSend,
  cancelScheduled,
  undoSend,
  summarizeThread,
  triageThread,
  draftReply,
  bulkTriage,
  classifyThreads,
  generateDailyReportTool,
  getLatestDailyReportTool,
  listDailyReportsTool,
  getDailyReportTool,
  listSmartLabels,
  createSmartLabel,
  previewSmartLabel,
  updateSmartLabel,
  deleteSmartLabel,
  listSmartRules,
  createSmartRule,
  setSmartRuleEnabledTool,
  trackThread,
  updateTrackedThreadTool,
  resolveTrackedThread,
  listTrackedThreadsTool,
  getTrackedThreadTool,
  extractActionItems,
  translateThread,
  preSendCritique,
  nlSearch,
  remember,
  recall,
  forget,
  listMemories,
  calendarFreeBusy,
  calendarSuggestTimes,
  calendarCreateEvent,
  calendarListCalendars,
  calendarListEvents,
  calendarSyncNow,
  calendarUpdateEvent,
  calendarDeleteEvent,
  calendarDeleteRecurringSeries,
  calendarRsvpEvent,
  calendarGetPrimary,
  calendarUnsubscribeCalendar,
  contactLookup,
  expandAlias,
  resolvePhotos,
  browserbaseSearch,
  browserbaseFetch,
  logAction,
  listAuditEntries,
  listRecentOperationsTool,
  undoOperationTool,
  tasksListBoards,
  tasksGetBoard,
  tasksCreateBoard,
  tasksCreateCard,
  tasksUpdateCard,
  tasksMoveCard,
  tasksDeleteCard,
  tasksCreateColumn,
  tasksRenameColumn,
  tasksDeleteColumn,
  tasksRenameBoard,
  tasksDeleteBoard,
  tasksAddComment,
  tasksAttachLink,
  tasksAttachFile,
  // UI tools — server returns ack, client intercepts for the real mutation.
  uiFocusThread,
  uiSetQuery,
  uiOpenCompose,
  uiOpenReply,
  uiToast,
  uiCloseBar,
  uiSwitchAccount,
];

export const TOOLS: Record<string, AnyTool> = Object.fromEntries(allTools.map((t) => [t.name, t]));

export function listToolMetadata() {
  return allTools.map((t) => ({
    name: t.name,
    description: t.description,
    category: t.category,
    mutating: t.mutating,
  }));
}

export function getTool(name: string): AnyTool | null {
  return TOOLS[name] || null;
}
