import {
  bulkTriage,
  draftReply,
  extractActionItems,
  nlSearch,
  nlTask,
  preSendCritique,
  summarizeThread,
  translateThread,
  triageThread,
} from './ai';
import {
  albatrossApplyIntentPlan,
  albatrossApproveAction,
  albatrossCaptureWork,
  albatrossCompleteWork,
  albatrossCreateProject,
  albatrossCreateRoutine,
  albatrossCreateSprint,
  albatrossGetProjectPane,
  albatrossGetWorkContext,
  albatrossListAdd,
  albatrossListApprovalQueue,
  albatrossListProjects,
  albatrossListRoutines,
  albatrossListSprints,
  albatrossMetricLog,
  albatrossRecordProgress,
  albatrossRejectAction,
  albatrossReplanWork,
  albatrossRunRoutineNow,
  albatrossSetRoutineConsent,
  albatrossSplitWork,
  albatrossUpdateProject,
} from './albatross';
import {
  areaAddFact,
  areaArchive,
  areaArtifactSetStatus,
  areaCreate,
  areaDiscoverContext,
  areaDomainActivity,
  areaFactSetStatus,
  areaHome,
  areaList,
  areaUpdateIdentity,
  workHome,
  workList,
} from './areas';
import {
  calendarCountEvents,
  calendarCreateEvent,
  calendarDeleteEvent,
  calendarDeleteRecurringSeries,
  calendarEventDetail,
  calendarFreeBusy,
  calendarGetPrimary,
  calendarListCalendars,
  calendarListEvents,
  calendarRsvpEvent,
  calendarSearchEvents,
  calendarSuggestTimes,
  calendarSyncNow,
  calendarUnsubscribeCalendar,
  calendarUpdateEvent,
} from './calendar';
import {
  cancelScheduled,
  deleteDraftTool,
  forwardMessage,
  listDraftsTool,
  listScheduled,
  replyAllMessage,
  replyMessage,
  saveDraftTool,
  scheduleSend,
  sendMessage,
  undoSend,
  updateDraft,
} from './compose';
import { contactLookup, expandAlias } from './contacts';
import { contentSearch } from './content';
import { corpusCount, corpusSearch, senderProfile, threadTimeline } from './corpus';
import {
  dismissDailyReportTaskTool,
  dismissDailyReportThreadTool,
  generateDailyReportTool,
  getDailyReportTool,
  getLatestDailyReportTool,
  listDailyReportsTool,
  listDailyReportTaskDismissalsTool,
  listDailyReportThreadDismissalsTool,
  restoreDailyReportTaskTool,
  restoreDailyReportThreadTool,
} from './daily-report';
import { DISPLAY_TOOLS } from './display';
import {
  documentApplyInstruction,
  documentCreate,
  documentEdit,
  documentExport,
  documentGet,
  documentList,
  documentPublishGoogle,
  documentReviewSlides,
  documentSuggestChanges,
  spreadsheetCapabilitiesTool,
} from './documents';
import { cloudFileSearch, googleFileImport } from './files';
import { googleDocumentEdit, googleDocumentGet } from './google-documents';
import {
  getMessage,
  getThread,
  listAccounts,
  listAccountThreads,
  listAttachments,
  listLabels,
  listSmartCategory,
  listSnoozed,
  readThread,
  searchThreads,
} from './mail';
import {
  addLabel,
  applySmartLabels,
  archiveThread,
  bulkMoveThreads,
  createLabel,
  markRead,
  markThreadRead,
  markUnread,
  muteThread,
  removeLabel,
  restoreFromTrash,
  snoozeThreadTool,
  starMessage,
  trashThread,
  unsnoozeThreadTool,
  unstarMessage,
} from './mail-mutate';
import { blockSenderTool, getUnsubscribeOptions, listSenderCleanup, unsubscribeSender } from './mail-senders';
import {
  deleteSavedReplyTool,
  listSavedRepliesTool,
  listSignaturesTool,
  saveSavedReplyTool,
  setSignatureTool,
} from './mail-templates';
import { getVoiceProfileTool, learnVoiceProfileTool, updateVoiceProfileTool } from './mail-voice';
import { githubSearch, mcpConnectionStatus, mcpCreateTask, mcpListItems, mcpSearch } from './mcp';
import { forget, listMemories, recall, remember } from './memories';
import { NARRATIVE_TOOLS } from './narrative';
import { listRecentOperationsTool, undoOperationTool } from './operations-tools';
import { resolvePhotos } from './photos';
import { presentationPlan } from './presentations';
import type { AnyTool } from './registry';
import { salvageContext } from './salvage';
import {
  applySmartCorrection,
  createSmartLabel,
  createSmartRule,
  deleteSmartLabel,
  listSmartLabels,
  listSmartRules,
  previewSmartLabel,
  setSmartRuleEnabledTool,
  updateSmartLabel,
} from './smart-labels';
import {
  tasksAddComment,
  tasksAttachCalendarEventLink,
  tasksAttachFile,
  tasksAttachLink,
  tasksCreateBoard,
  tasksCreateCard,
  tasksCreateColumn,
  tasksDeleteBoard,
  tasksDeleteCard,
  tasksDeleteColumn,
  tasksDueCards,
  tasksForCalendarEvent,
  tasksForThread,
  tasksGetBoard,
  tasksGetCard,
  tasksInviteMember,
  tasksListBoards,
  tasksMoveCard,
  tasksRemoveMember,
  tasksRenameBoard,
  tasksRenameColumn,
  tasksReorderColumn,
  tasksSetPublicLink,
  tasksUpdateCard,
} from './tasks';
import { resolveTrackedThread, updateTrackedThreadTool } from './tracked-threads';
import {
  uiCloseBar,
  uiFocusThread,
  uiOpenCompose,
  uiOpenReply,
  uiSetQuery,
  uiSwitchAccount,
  uiToast,
} from './ui-tools';
import { browserbaseFetch, browserbaseSearch } from './web';
import { wordDocumentCreate, wordDocumentEdit, wordDocumentGet } from './word-documents';

const allTools: AnyTool[] = [
  mcpSearch,
  githubSearch,
  mcpListItems,
  mcpConnectionStatus,
  mcpCreateTask,
  listAccounts,
  searchThreads,
  corpusSearch,
  contentSearch,
  senderProfile,
  corpusCount,
  threadTimeline,
  listSmartCategory,
  getThread,
  readThread,
  getMessage,
  listLabels,
  listAttachments,
  listAccountThreads,
  archiveThread,
  trashThread,
  restoreFromTrash,
  bulkMoveThreads,
  getUnsubscribeOptions,
  unsubscribeSender,
  blockSenderTool,
  listSenderCleanup,
  markRead,
  markThreadRead,
  markUnread,
  starMessage,
  unstarMessage,
  addLabel,
  removeLabel,
  createLabel,
  applySmartLabels,
  applySmartCorrection,
  muteThread,
  snoozeThreadTool,
  unsnoozeThreadTool,
  listSnoozed,
  sendMessage,
  replyMessage,
  replyAllMessage,
  forwardMessage,
  saveDraftTool,
  updateDraft,
  deleteDraftTool,
  listDraftsTool,
  listScheduled,
  scheduleSend,
  cancelScheduled,
  undoSend,
  listSignaturesTool,
  setSignatureTool,
  listSavedRepliesTool,
  saveSavedReplyTool,
  deleteSavedReplyTool,
  getVoiceProfileTool,
  updateVoiceProfileTool,
  learnVoiceProfileTool,
  summarizeThread,
  triageThread,
  draftReply,
  bulkTriage,
  generateDailyReportTool,
  getLatestDailyReportTool,
  listDailyReportsTool,
  getDailyReportTool,
  dismissDailyReportTaskTool,
  listDailyReportTaskDismissalsTool,
  dismissDailyReportThreadTool,
  listDailyReportThreadDismissalsTool,
  restoreDailyReportTaskTool,
  restoreDailyReportThreadTool,
  listSmartLabels,
  createSmartLabel,
  previewSmartLabel,
  updateSmartLabel,
  deleteSmartLabel,
  listSmartRules,
  createSmartRule,
  setSmartRuleEnabledTool,
  updateTrackedThreadTool,
  resolveTrackedThread,
  presentationPlan,
  documentCreate,
  documentEdit,
  wordDocumentCreate,
  wordDocumentGet,
  wordDocumentEdit,
  documentList,
  documentGet,
  documentSuggestChanges,
  spreadsheetCapabilitiesTool,
  documentApplyInstruction,
  documentReviewSlides,
  documentPublishGoogle,
  documentExport,
  cloudFileSearch,
  googleFileImport,
  googleDocumentGet,
  googleDocumentEdit,
  extractActionItems,
  translateThread,
  preSendCritique,
  nlSearch,
  nlTask,
  remember,
  recall,
  forget,
  listMemories,
  calendarFreeBusy,
  calendarSuggestTimes,
  calendarCreateEvent,
  calendarListCalendars,
  calendarListEvents,
  calendarSearchEvents,
  calendarCountEvents,
  calendarEventDetail,
  calendarSyncNow,
  calendarUpdateEvent,
  calendarDeleteEvent,
  calendarDeleteRecurringSeries,
  calendarRsvpEvent,
  calendarGetPrimary,
  calendarUnsubscribeCalendar,
  contactLookup,
  expandAlias,
  resolvePhotos,
  browserbaseSearch,
  browserbaseFetch,
  listRecentOperationsTool,
  undoOperationTool,
  tasksListBoards,
  tasksGetBoard,
  tasksGetCard,
  tasksForThread,
  tasksForCalendarEvent,
  tasksDueCards,
  albatrossApplyIntentPlan,
  albatrossListApprovalQueue,
  albatrossApproveAction,
  albatrossRejectAction,
  albatrossCreateProject,
  albatrossListProjects,
  albatrossUpdateProject,
  albatrossCreateRoutine,
  albatrossListRoutines,
  albatrossSetRoutineConsent,
  albatrossRunRoutineNow,
  albatrossGetProjectPane,
  albatrossCreateSprint,
  albatrossListSprints,
  albatrossGetWorkContext,
  albatrossCompleteWork,
  albatrossRecordProgress,
  albatrossReplanWork,
  albatrossSplitWork,
  albatrossListAdd,
  albatrossMetricLog,
  albatrossCaptureWork,
  salvageContext,
  areaList,
  areaHome,
  workHome,
  workList,
  areaCreate,
  areaDiscoverContext,
  areaUpdateIdentity,
  areaArchive,
  areaArtifactSetStatus,
  areaAddFact,
  areaFactSetStatus,
  areaDomainActivity,
  tasksCreateBoard,
  tasksCreateCard,
  tasksUpdateCard,
  tasksMoveCard,
  tasksDeleteCard,
  tasksCreateColumn,
  tasksRenameColumn,
  tasksReorderColumn,
  tasksDeleteColumn,
  tasksRenameBoard,
  tasksDeleteBoard,
  tasksSetPublicLink,
  tasksInviteMember,
  tasksRemoveMember,
  tasksAddComment,
  tasksAttachCalendarEventLink,
  tasksAttachLink,
  tasksAttachFile,
  // UI tools — server returns ack, client intercepts for the real mutation.
  uiFocusThread,
  uiSetQuery,
  uiOpenCompose,
  uiOpenReply,
  uiToast,
  uiCloseBar,
  uiSwitchAccount,
  // Display tools — validated payloads rendered as rich tool-ui components in
  // chat (weather, charts, tables, code, media, maps, drafts…).
  ...DISPLAY_TOOLS,
  ...NARRATIVE_TOOLS,
];

export const TOOLS: Record<string, AnyTool> = Object.fromEntries(allTools.map((t) => [t.name, t]));

export function listToolMetadata() {
  return allTools.map((t) => ({
    name: t.name,
    description: t.description,
    category: t.category,
    mutating: t.mutating,
  }));
}

export function getTool(name: string): AnyTool | null {
  return TOOLS[name] || null;
}
